---
# vars file for platform

iot_edge_agent:
  repo: "https://github.com/One-Green/iot-edge-agent.git"
  version: "{{ iot_edge_agent_version | default('master') }}"
  dest: "/srv/iot_node_agent"

mqtt_host: ""
mqtt_port: ""
mqtt_user: ""
mqtt_password: ""
