---
# Author Shanmugathas Vigneswaran
# tasks file for platform

- name: Clean node agent
  block:
    - name: clean /tmp
      shell: /bin/rm -rf /tmp/*
    - name: clean logs
      shell: /bin/rm -f /var/log/*/*.log
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

- name: Install binaries (python,pip,sqlite3...)
  apt:
    name:
      - python3-dev
      - python3-pip
      - sqlite3
      - wget
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Ensure pm2 is installed
  block:
    - name: Check pm2 exist
      shell: "which pm2"
  rescue:
    - name: Resize /tmp 246M > 500M
      shell: "mount -o remount,size=500M /tmp/"
    - name: Install pm2
      shell: "wget -qO- https://getpm2.com/install.sh | bash"
    - name: clean /tmp
      shell: "/bin/rm -rf /tmp/*"
    - name: "Resize /tmp 500M > 246M"
      shell: "mount -o remount,size=246M /tmp/"

- name: pm2 autostart node agent at startup
  shell: "pm2 startup"

- name: "Git clone iot-edge-agent version: {{ iot_edge_agent.version}} > {{ iot_edge_agent.dest }}"
  ansible.builtin.git:
    repo: "{{ iot_edge_agent.repo }}"
    dest: "{{ iot_edge_agent.dest }}"
    version: "{{ iot_edge_agent.version }}"

- name: Install Python requirements
  pip:
    requirements: "{{ iot_edge_agent.dest }}/requirements.txt"
    executable: pip3
